---
  parsing: 
    xpath: 
      name: "/project/title/text()"
    regexp: 
      qualification: "<qualification>(.*)</qualification>"
  mapping: 
    - 
      request: 
        method: "POST"
        url: "/test/post"
        header: 
          Content-Type: "text/plain"
        content: 
          name: "The project"
          qualification: 
            - "8"
            - "0"
      response: 
        content: "Hello POST with XML"
    - 
      request: 
        method: "GET"
        url: "/test/get"
      response: 
        content: "Hello GET"
